global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'server'
    metrics_path: /metrics
    static_configs:
      - targets: ['server:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - /etc/prometheus/rules.yml
